name: Download and Deploy Site

on:
  workflow_dispatch:
    inputs:
      site_url:
        description: 'URL of the site to download'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
        
    - name: Download site
      run: npm run download
      env:
        SITE_URL: ${{ github.event.inputs.site_url }}
        
    - name: Deploy to Permaweb
      run: npm run deploy
      env:
        DEPLOY_ANT_PROCESS: ${{ secrets.DEPLOY_ANT_PROCESS }}
